name: gif pr commenter

on:
  pull_request:
    paths:
      - 'vhs.tape'

permissions:
  contents: write

jobs:
  gif-pr:
    permissions:
      pull-requests: write # for amannn/action-semantic-pull-request to analyze PRs
      statuses: write # for amannn/action-semantic-pull-request to mark status of analyzed PR
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        id: vhs_step
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: vhs.tape
          output: vhs.gif
          publish: true
      
      - uses: actions/github-script@v7
        with:
          script: |
            async function upsertComment(owner, repo, issue_number, purpose, body) {
              const {data: comments} = await github.rest.issues.listComments(
                {owner, repo, issue_number});
              const marker = `<!-- bot: ${purpose} -->`;
              body = marker + "\n" + body;
              const existing = comments.filter((c) => c.body.includes(marker));
              if (existing.length > 0) {
                const last = existing[existing.length - 1];
                core.info(`Updating comment ${last.id}`);
                await github.rest.issues.updateComment({
                  owner, repo,
                  body,
                  comment_id: last.id,
                });
              } else {
                core.info(`Creating a comment in issue / PR #${issue_number}`);
                await github.rest.issues.createComment({issue_number, body, owner, repo});
              }
            }

            const {owner, repo} = context.repo;
            const issue_number = context.issue.number;

            // Use the output from the vhs_step to set the comment body
            const body = `Here's the generated GIF:\n\n![Generated GIF](${{ steps.vhs_step.outputs.gif-url }})`;
            core.info("Review thread message body:", body);
            await upsertComment(owner, repo, issue_number, "gif-commenter", body);